swagger: '2.0'
info:
  description: This is a mock-mock server. Manage mock-mocks for motivated people.
  version: 0.0.1
  title: mock-mock
host: mock-mock.swagger.io
basePath: /v1
tags:
  - name: mock-mock
    description: manage mock-mocks. start, end, and performances.
schemes:
  # - https
  - http
consumes:
  - application/json
paths:
  /:
    get:
      tags:
        - health
      summary: health check
      description: some
      operationId: hello
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Health'
  /health:
    get:
      tags:
        - health
      summary: health check
      description: some
      operationId: healthcheck
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Health'
  /mock:
    post:
      tags:
        - mock
      summary: Request any mock-mock action
      description: some
      parameters:
        - in: body
          name: body
          description: Slack information object, requested from slash command.
          required: true
          schema:
            $ref: '#/definitions/SlackRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/SlackResponse'
        405:
          description: Invalid input
definitions:
  SlackRequest:
    type: object
    properties:
      token:
        type: string
      team_id:
        type: string
      team_domain:
        type: string
      channel_id:
        type: string
      channel_name:
        type: string
      user_id:
        type: string
      user_name:
        type: string
      command:
        type: string
      text:
        type: string
      response_url:
        type: string
      trigger_id:
        type: string
  SlackResponse:
    type: object
    properties:
      message:
        type: string
  Health:
    type: object
    properties:
      message:
        type: string # Error Message