// Code generated by go-swagger; DO NOT EDIT.

package mock_mock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostMockHandlerFunc turns a function with the right signature into a post mock handler
type PostMockHandlerFunc func(PostMockParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMockHandlerFunc) Handle(params PostMockParams) middleware.Responder {
	return fn(params)
}

// PostMockHandler interface for that can handle valid post mock params
type PostMockHandler interface {
	Handle(PostMockParams) middleware.Responder
}

// NewPostMock creates a new http.Handler for the post mock operation
func NewPostMock(ctx *middleware.Context, handler PostMockHandler) *PostMock {
	return &PostMock{Context: ctx, Handler: handler}
}

/*PostMock swagger:route POST /mock mock-mock postMock

Request any mock-mock action

*/
type PostMock struct {
	Context *middleware.Context
	Handler PostMockHandler
}

func (o *PostMock) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostMockParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
